---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3000586598-oXwCZA9qZgfxub2vznOC1maaJLzCFcF7GmQsVjQ
:access_token_secret: Px9LivC27vdb2VtxW3T00rQdwWldWvbd2NupKfnbd5RB3
